version: '3.9'

services:
  postgres:
    container_name: shop_postgres
    image: "postgres:${PG_VERSION}"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
      - PGSSLMODE=${PG_SSLMODE}
    ports:
      - "${PG_PORT}:5432"

volumes:
  db-data:
